In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [21]:
df = pd.read_csv('../data/raw/diabetes.csv')

In [22]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [23]:
df.shape


(768, 9)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [25]:
df.describe().T

count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

In [26]:
df["Glucose"].replace(0, np.nan, inplace=True)
df["BloodPressure"].replace(0, np.nan, inplace=True)
df["Insulin"].replace(0, np.nan, inplace=True)

df["SkinThickness"].replace(0, np.nan, inplace=True)

/tmp/ipykernel_44346/3448885594.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Glucose"].replace(0, np.nan, inplace=True)
/tmp/ipykernel_44346/3448885594.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try 

In [28]:
df["BMI"] = df["BMI"].replace(0, np.nan)


In [33]:
df.describe().T


count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   763.0  121.686763   30.535641  44.000  99.00000   
BloodPressure             733.0   72.405184   12.382158  24.000  64.00000   
SkinThickness             541.0   29.153420   10.476982   7.000  22.00000   
Insulin                   394.0  155.548223  118.775855  14.000  76.25000   
BMI                       757.0   32.457464    6.924988  18.200  27.50000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  141.00000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              29.0000   36.00000   99.00  
Insulin                   125.0000  190.00000  846.00  
BMI                        32.3000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

In [32]:
from sklearn.impute import SimpleImputer

In [38]:
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp.fit(df["SkinThickness"].values.reshape(-1, 1))

df["SkinThickness"] = imp.transform(df["SkinThickness"].values.reshape(-1, 1))


In [40]:
df["SkinThickness"].describe().T

count    768.000000
mean      29.994792
std        8.886506
min        7.000000
25%       25.000000
50%       32.000000
75%       32.000000
max       99.000000
Name: SkinThickness, dtype: float64

In [42]:
df["SkinThickness"].isnull().sum()

np.int64(0)

In [43]:
imp = SimpleImputer(missing_values=np.nan, strategy='median')
df["Glucose"] = imp.fit_transform(df["Glucose"].values.reshape(-1, 1))
df["Glucose"].describe().T

count    768.000000
mean     121.656250
std       30.438286
min       44.000000
25%       99.750000
50%      117.000000
75%      140.250000
max      199.000000
Name: Glucose, dtype: float64

In [44]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
df["BloodPressure"] = imp.fit_transform(df["BloodPressure"].values.reshape(-1, 1))
df["BloodPressure"].describe().T

count    768.000000
mean      72.405184
std       12.096346
min       24.000000
25%       64.000000
50%       72.202592
75%       80.000000
max      122.000000
Name: BloodPressure, dtype: float64

In [45]:
imp = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=32)

df["BMI"] = imp.fit_transform(df["BMI"].values.reshape(-1, 1))
df["BMI"].describe().T

count    768.000000
mean      32.450911
std        6.875366
min       18.200000
25%       27.500000
50%       32.000000
75%       36.600000
max       67.100000
Name: BMI, dtype: float64

In [46]:
df.isnull().sum()


Pregnancies                   0
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                     374
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [48]:
df.to_csv("../data/interim/diabetes_imputed.csv", index=False)

In [50]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [61]:
imp = IterativeImputer(max_iter=10, random_state=42)


In [58]:
features = [
    [4, 2, 1],
    [24, 12, 6],
    [8, np.nan, 2],
    [28, 14, 7],
    [32, 16, np.nan],
    [600, 300, 150],
    [np.nan, 60, 30],
    [np.nan, np.nan, 1]
]

In [62]:
imp.fit(features)

IterativeImputer(random_state=42)

In [64]:
imp.transform(features)

array([[  4.        ,   2.        ,   1.        ],
       [ 24.        ,  12.        ,   6.        ],
       [  8.        ,   3.99966002,   2.        ],
       [ 28.        ,  14.        ,   7.        ],
       [ 32.        ,  16.        ,   7.92735309],
       [600.        , 300.        , 150.        ],
       [120.00314828,  60.        ,  30.        ],
       [  5.58961603,   2.79614869,   1.        ]])

In [84]:
imp = IterativeImputer(max_iter=10000, random_state=42)

In [85]:
features = df.drop(columns=["Outcome"])
label = df["Outcome"]

In [86]:
imp.fit(features)


IterativeImputer(max_iter=10000, random_state=42)

In [87]:
arr = imp.transform(features)

In [88]:
arr.shape

(768, 8)

In [89]:
df_features = pd.DataFrame(arr, columns=features.columns)

In [90]:
df_features.describe().T

count        mean        std        min        25%  \
Pregnancies               768.0    3.845052   3.369578   0.000000   1.000000   
Glucose                   768.0  121.656250  30.438286  44.000000  99.750000   
BloodPressure             768.0   72.405184  12.096346  24.000000  64.000000   
SkinThickness             768.0   29.994792   8.886506   7.000000  25.000000   
Insulin                   768.0  152.815064  97.206638 -16.568152  89.976015   
BMI                       768.0   32.450911   6.875366  18.200000  27.500000   
DiabetesPedigreeFunction  768.0    0.471876   0.331329   0.078000   0.243750   
Age                       768.0   33.240885  11.760232  21.000000  24.000000   

                                 50%         75%     max  
Pregnancies                 3.000000    6.000000   17.00  
Glucose                   117.000000  140.250000  199.00  
BloodPressure              72.202592   80.000000  122.00  
SkinThickness              32.000000   32.000000   99.00  
Insulin                   131.100779  189.857469  846.00  
BMI                        32.000000   36.600000   67.10  
DiabetesPedigreeFunction    0.372500    0.626250    2.42  
Age                        29.000000   41.000000   81.00

In [83]:
df["Insulin"].describe().T

count    394.000000
mean     155.548223
std      118.775855
min       14.000000
25%       76.250000
50%      125.000000
75%      190.000000
max      846.000000
Name: Insulin, dtype: float64

In [91]:
from sklearn.impute import MissingIndicator

In [92]:
features = [
    [4, 2, 1],
    [24, 12, 6],
    [8, 4, 2],
    [28, 14, 7],
    [32, 16, -1],
    [600, 300, 150],
    [-1, 60, 30],
    [-1, 4, 1]
]

In [94]:
imp = MissingIndicator(missing_values=-1)

In [96]:
mask_missing_values_only = imp.fit_transform(features)

In [99]:
mask_missing_values_only

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [ True, False],
       [ True, False]])

In [101]:
imp.features_

array([0, 2])

In [103]:
imp = MissingIndicator(missing_values=-1, features="all")

In [104]:
mask_all = imp.fit_transform(features)

In [106]:
mask_all

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [108]:
imp.features_

array([0, 1, 2])

In [126]:
features = df_features
label = df["Outcome"]


In [127]:
mask = np.random.randint(0, 100, size=features.shape).astype(bool)

In [128]:
mask = np.logical_not(mask)


In [129]:
mask

array([[False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], shape=(768, 8))

In [131]:
features[mask] = np.nan


In [132]:

features

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0            6.0    148.0           72.0           35.0  219.028414  33.6   
1            1.0     85.0           66.0           29.0   70.341550  26.6   
2            8.0    183.0           64.0           32.0  270.573172  23.3   
3            1.0     89.0           66.0           23.0   94.000000  28.1   
4            0.0    137.0           40.0           35.0  168.000000  43.1   
..           ...      ...            ...            ...         ...   ...   
763         10.0    101.0           76.0           48.0  180.000000  32.9   
764          2.0    122.0           70.0           27.0  158.510349  36.8   
765          5.0    121.0           72.0           23.0  112.000000  26.2   
766          1.0    126.0           60.0           32.0  174.634129  30.1   
767          1.0     93.0           70.0           31.0   87.173370  30.4   

     DiabetesPedigreeFunction   Age  
0                         NaN  50.0  
1                       0.351  31.0  
2                       0.672  32.0  
3                       0.167  21.0  
4                       2.288  33.0  
..                        ...   ...  
763                     0.171  63.0  
764                     0.340  27.0  
765                     0.245  30.0  
766                     0.349  47.0  
767                     0.315  23.0  

[768 rows x 8 columns]

In [144]:
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [140]:
X = features
y = label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [159]:
transformer = ColumnTransformer(
    transformers=[
        ("Features", SimpleImputer(strategy="mean"), [0, 2, 3, 4, 5, 6, 7]),
        ("Glucose", SimpleImputer(strategy="median"), ["Glucose"])
    ]
)

In [160]:
model = make_pipeline(transformer, DecisionTreeClassifier(max_depth=4))

In [161]:
model.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('Features', SimpleImputer(),
                                                  [0, 2, 3, 4, 5, 6, 7]),
                                                 ('Glucose',
                                                  SimpleImputer(strategy='median'),
                                                  ['Glucose'])])),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=4))])

In [162]:
model.score(X_train, y_train)

0.8257328990228013

In [163]:
from sklearn.metrics import accuracy_score

In [164]:
accuracy = accuracy_score(model.predict(X_test), y_test)

In [166]:
accuracy


0.7077922077922078